# Generated by Django 3.2.7 on 2021-09-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210924_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date_published',
            new_name='published_at',
        ),
    ]
