# Generated by Django 3.2.7 on 2021-10-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('serie', 'Serie'), ('music', 'Music'), ('game', 'Game'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
